### ISSUE TITLE
Criação dos projetos com gerenciador de dependências

### ISSUE THREAD

**Issue by samuelcomputacao** [ArthurFerrao/devweb#1]
Nas próximas atividades é preciso criar os projetos com um gerenciador de dependências. 

Aconselho a utilização do gerenciador de dependências [yarn](https://yarnpkg.com/getting-started)

- [Aqui](https://create-react-app.dev/docs/getting-started/) é possível ver algumas formas de criar um projeto frontend.

- [Aqui](https://classic.yarnpkg.com/en/docs/creating-a-package/) é possível ver algumas formas de criar um projeto backend.

**Comment by ArthurFerrao** [comment]
Obrigado pela sugestão, vou dar uma olhada nos links
